repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.4.2
    hooks:
    # Run the linter.
    -   id: ruff
        args: [--fix]
    # Run the formatter.
    -   id: ruff-format
-   repo: https://github.com/python-poetry/poetry
    rev: 1.8.3
    hooks:
    -   id: poetry-check
        stages: [commit]
        args: ["--lock"]
    -   id: poetry-lock
        stages: [commit]
        args: ["--no-update"]
    -   id: poetry-export
        stages: [commit]
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
